language: node_js
node_js:
    - 10

services:
    - docker

before_install:
    - docker build -t feed-api .
    - docker tag feed-api anuardocker/feed-api:latest

deploy:
    provider: script
    script: bash docker_push
    on:
        branch: main